repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
      - id: mypy
        args: [--show-error-codes,
               --warn-redundant-casts,
               --warn-return-any,
               --warn-unreachable,
        ]
        files: naslib/.*
        exclude: 
          - naslib/examples/.*
          - naslib/docs/.*
          
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-print==3.1.4
          - flake8-import-order
        name: flake8 naslib
        files: naslib/.*
        exclude: 
          - naslib/examples/.*
          - naslib/docs/.*
          - naslib/predictors/.*
      - id: flake8
        additional_dependencies:
          - flake8-print==3.1.4
          - flake8-import-order
        name: flake8 test
        files: tests/.*