site_name: JAHS-Bench-201 Documentation
docs_dir: docs
repo_url: https://github.com/automl/jahs_bench_201
repo_name: automl/jahs_bench_201
edit_uri: ""

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list

nav:
  - Introduction and Installation: "README.md"
  - Design Space: "search_space.md"
  - Querying the Benchmark: "usage.md"
  - Evaluation Protocol: "evaluation_protocol.md"
  - Leaderboards: "leaderboards.md"
  - Details on Performance Dataset: "performance_dataset.md"
  - Details on Surrogate Models: "surrogate.md"
  - Author Statement: "authorstatement.md"

# extra:
#  version:
#    provider: mike
